"""create initial tables

Revision ID: 5fe5dd45c07f
Revises: i8j9k0l1m2n3
Create Date: 2026-03-25 09:30:54.602691

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5fe5dd45c07f'
down_revision: Union[str, None] = 'i8j9k0l1m2n3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_attachments_entity'), table_name='attachments')
    op.drop_table('attachments')
    op.drop_table('system_settings')
    op.drop_table('custom_field_defs')
    op.drop_constraint(op.f('uq_quotes_access_token'), 'quotes', type_='unique')
    op.drop_index(op.f('ix_quotes_access_token'), table_name='quotes')
    op.create_index(op.f('ix_quotes_access_token'), 'quotes', ['access_token'], unique=True)
    op.drop_index(op.f('ix_saved_views_user_entity'), table_name='saved_views')
    op.drop_index(op.f('ix_sequence_enrollments_entity'), table_name='sequence_enrollments')
    op.alter_column('workflows', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('workflows', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('workflows', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('workflows', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_sequence_enrollments_entity'), 'sequence_enrollments', ['entity_type', 'entity_id'], unique=False)
    op.create_index(op.f('ix_saved_views_user_entity'), 'saved_views', ['user_id', 'entity_type'], unique=False)
    op.drop_index(op.f('ix_quotes_access_token'), table_name='quotes')
    op.create_index(op.f('ix_quotes_access_token'), 'quotes', ['access_token'], unique=False)
    op.create_unique_constraint(op.f('uq_quotes_access_token'), 'quotes', ['access_token'], postgresql_nulls_not_distinct=False)
    op.create_table('custom_field_defs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('label_en', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('label_de', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('field_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('applies_to', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('options', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('is_required', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('field_order', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('custom_field_defs_pkey'))
    )
    op.create_table('system_settings',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('key', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('value', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('system_settings_pkey')),
    sa.UniqueConstraint('key', name=op.f('system_settings_key_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('attachments',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('entity_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('entity_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('original_name', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('stored_name', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('mime_type', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('file_size', sa.BIGINT(), server_default=sa.text("'0'::bigint"), autoincrement=False, nullable=False),
    sa.Column('has_thumbnail', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('uploaded_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], name=op.f('attachments_uploaded_by_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('attachments_pkey')),
    sa.UniqueConstraint('stored_name', name=op.f('attachments_stored_name_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_attachments_entity'), 'attachments', ['entity_type', 'entity_id'], unique=False)
    # ### end Alembic commands ###
